"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { BadgeIndianRupee, BedDouble, CalendarRange, CreditCard, KeyRound, Plus, Save, ShieldCheck, UserCog, UsersRound } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Switch } from "@/components/ui/switch";
import { money } from "./domain";

type Rate = { id: string; roomKey: string; roomName: string; baseRate: number; includedAdults: number; extraAdultRate: number; childRate: number; active: boolean };
type Season = { id: string; name: string; startDate: string; endDate: string; adjustmentPercent: number; priority: number; active: boolean };
type PaymentAccount = { id?: string; provider: string; displayName: string; merchantId: string; keyId: string; upiId: string; settlementAccountMask: string; mode: string; active: boolean };
type Staff = { id: string; email: string; fullName: string; phone: string; role: string; status: string; createdAt: string };
type UnitConfig = { id: string; name: string; type: "Cottage" | "Room"; parent?: string | null; capacityAdults: number; capacityChildren: number; rate: number; housekeepingStatus: string; active: boolean };
const emptyPayment: PaymentAccount = { provider: "Razorpay", displayName: "Cardamom Rock payments", merchantId: "", keyId: "", upiId: "", settlementAccountMask: "", mode: "Test", active: false };
const roles = ["Admin", "Manager", "Front Desk", "Housekeeping", "Accounts", "Maintenance"];

export function AdminConsole({ onNotice }: { onNotice: (value: string) => void }) {
  const [rates, setRates] = useState<Rate[]>([]); const [seasons, setSeasons] = useState<Season[]>([]); const [staff, setStaff] = useState<Staff[]>([]);
  const [units, setUnits] = useState<UnitConfig[]>([]);
  const [payment, setPayment] = useState<PaymentAccount>(emptyPayment); const [authorized, setAuthorized] = useState<boolean | null>(null); const [busy, setBusy] = useState("");
  const flash = (message: string) => { onNotice(message); window.setTimeout(() => onNotice(""), 4200); };
  const load = async () => {
    const me = await fetch("/api/admin/me", { cache: "no-store" }); if (!me.ok) { setAuthorized(false); return; }
    const meData = await me.json() as { user: { role: string } }; if (meData.user.role !== "Admin") { setAuthorized(false); return; } setAuthorized(true);
    const [pricingResponse, staffResponse, paymentResponse, configurationResponse] = await Promise.all([fetch("/api/pricing", { cache: "no-store" }), fetch("/api/admin/staff", { cache: "no-store" }), fetch("/api/admin/payment-accounts", { cache: "no-store" }), fetch("/api/configuration", { cache: "no-store" })]);
    const pricing = await pricingResponse.json() as { rates?: Rate[]; seasons?: Season[] }; const staffData = await staffResponse.json() as { staff?: Staff[] }; const paymentData = await paymentResponse.json() as { accounts?: PaymentAccount[] }; const configuration = await configurationResponse.json() as { units?: UnitConfig[] };
    setRates(pricing.rates ?? []); setSeasons(pricing.seasons ?? []); setStaff(staffData.staff ?? []); setPayment(paymentData.accounts?.[0] ?? emptyPayment); setUnits(configuration.units ?? []);
  };
  // Synchronize the administration console with persisted property controls.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { void load(); }, []);
  const savePricing = async (type: "rate" | "season", record: Rate | Season) => { setBusy(record.id); try { const response = await fetch("/api/pricing", { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify({ type, ...record }) }); const data = await response.json() as { rates?: Rate[]; seasons?: Season[]; error?: string }; if (!response.ok) throw new Error(data.error || "Unable to save pricing."); setRates(data.rates ?? []); setSeasons(data.seasons ?? []); flash(`${type === "rate" ? "Room rate" : "Season rule"} saved.`); } catch (error) { flash(error instanceof Error ? error.message : "Unable to save pricing."); } finally { setBusy(""); } };
  const savePayment = async () => { setBusy("payment"); try { const response = await fetch("/api/admin/payment-accounts", { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify(payment) }); const data = await response.json() as { accounts?: PaymentAccount[]; error?: string }; if (!response.ok) throw new Error(data.error || "Unable to save payment account."); setPayment(data.accounts?.[0] ?? payment); flash("Payment account configuration saved."); } catch (error) { flash(error instanceof Error ? error.message : "Unable to save payment account."); } finally { setBusy(""); } };
  const addStaff = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); setBusy("staff"); try { const response = await fetch("/api/admin/staff", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(Object.fromEntries(form)) }); const data = await response.json() as { staff?: Staff[]; error?: string }; if (!response.ok) throw new Error(data.error || "Unable to create staff access."); setStaff(data.staff ?? []); event.currentTarget.reset(); flash("Staff role created. Share private Site access with the same email to complete activation."); } catch (error) { flash(error instanceof Error ? error.message : "Unable to create staff access."); } finally { setBusy(""); } };
  const setStaffStatus = async (member: Staff) => { const status = member.status === "Active" ? "Suspended" : "Active"; const response = await fetch("/api/admin/staff", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ id: member.id, status }) }); const data = await response.json() as { staff?: Staff[]; error?: string }; if (!response.ok) { flash(data.error || "Unable to update staff access."); return; } setStaff(data.staff ?? []); flash(`${member.fullName} is now ${status.toLowerCase()}.`); };
  const saveUnit = async (unit: UnitConfig) => { setBusy(unit.id); try { const response = await fetch("/api/configuration", { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify({ ...unit, type: "unit", unitType: unit.type }) }); const data = await response.json() as { units?: UnitConfig[]; error?: string }; if (!response.ok) throw new Error(data.error || "Unable to save room."); setUnits(data.units ?? []); flash(`${unit.name} configuration saved.`); } catch (error) { flash(error instanceof Error ? error.message : "Unable to save room."); } finally { setBusy(""); } };
  const addUnit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); setBusy("new-unit"); try { const response = await fetch("/api/configuration", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ type: "unit", ...Object.fromEntries(form) }) }); const data = await response.json() as { units?: UnitConfig[]; error?: string }; if (!response.ok) throw new Error(data.error || "Unable to add room."); setUnits(data.units ?? []); event.currentTarget.reset(); flash("New accommodation added and made available to reservations and pricing."); } catch (error) { flash(error instanceof Error ? error.message : "Unable to add room."); } finally { setBusy(""); } };
  const projectedRates = useMemo(() => rates.map((rate) => ({ name: rate.roomName, base: rate.baseRate, peak: Math.round(rate.baseRate * (1 + Math.max(0, ...seasons.map((season) => season.adjustmentPercent)) / 100)) })), [rates, seasons]);
  if (authorized === null) return <div className="rounded-2xl border bg-white p-10 text-center text-sm text-slate-500">Loading administrative controls…</div>;
  if (!authorized) return <div className="rounded-2xl border border-amber-200 bg-amber-50 p-6"><h1 className="text-xl font-bold text-amber-900">Administrator access required</h1><p className="mt-2 text-sm text-amber-800">Only an active Admin account can change rates, payment accounts or staff access.</p></div>;
  return <>
    <div className="mb-6"><p className="mb-1 text-xs font-bold uppercase tracking-[.14em] text-[#006ce4]">Protected configuration</p><h1 className="text-2xl font-bold tracking-tight sm:text-3xl">Admin console</h1><p className="mt-2 max-w-3xl text-sm text-slate-500">Control live room pricing, payment collection identity and staff access for Cardamom Rock.</p></div>
    <section className="mb-6 grid gap-4 md:grid-cols-3"><Metric icon={BadgeIndianRupee} label="Active room plans" value={String(rates.filter((item) => item.active).length)} /><Metric icon={CalendarRange} label="Season rules" value={String(seasons.filter((item) => item.active).length)} /><Metric icon={UsersRound} label="Active staff" value={String(staff.filter((item) => item.status === "Active").length)} /></section>
    <section className="space-y-6">
      <Panel title="Dynamic room pricing" description="Every quotation reads these base rates and the highest-priority matching season rule." icon={BadgeIndianRupee}>
        <div className="space-y-3">{rates.map((rate) => <div key={rate.id} className="grid gap-3 rounded-xl border p-4 md:grid-cols-[1fr_140px_120px_120px_90px_auto] md:items-end"><Field label="Room"><Input value={rate.roomName} onChange={(e) => setRates((current) => current.map((item) => item.id === rate.id ? { ...item, roomName: e.target.value } : item))} /></Field><NumberField label="Base/night" value={rate.baseRate} onChange={(value) => setRates((current) => current.map((item) => item.id === rate.id ? { ...item, baseRate: value } : item))} /><NumberField label="Extra adult" value={rate.extraAdultRate} onChange={(value) => setRates((current) => current.map((item) => item.id === rate.id ? { ...item, extraAdultRate: value } : item))} /><NumberField label="Child 6–12" value={rate.childRate} onChange={(value) => setRates((current) => current.map((item) => item.id === rate.id ? { ...item, childRate: value } : item))} /><Field label="Enabled"><Switch checked={Boolean(rate.active)} onCheckedChange={(active) => setRates((current) => current.map((item) => item.id === rate.id ? { ...item, active } : item))} /></Field><Button variant="outline" disabled={busy === rate.id} onClick={() => void savePricing("rate", rate)}><Save /> Save</Button></div>)}</div>
        <div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{projectedRates.map((item) => <div key={item.name} className="rounded-xl bg-blue-50 p-4"><span className="text-xs font-semibold text-slate-500">{item.name}</span><strong className="mt-1 block text-lg text-[#003b95]">{money(item.base)}</strong><span className="text-xs text-slate-500">Peak preview {money(item.peak)}</span></div>)}</div>
      </Panel>
      <Panel title="Season and demand rules" description="Use positive percentages for peak periods and negative percentages for offers." icon={CalendarRange}>
        <div className="space-y-3">{seasons.map((season) => <div key={season.id} className="grid gap-3 rounded-xl border p-4 md:grid-cols-[1fr_145px_145px_120px_90px_auto] md:items-end"><Field label="Season"><Input value={season.name} onChange={(e) => setSeasons((current) => current.map((item) => item.id === season.id ? { ...item, name: e.target.value } : item))} /></Field><Field label="From"><Input type="date" value={season.startDate} onChange={(e) => setSeasons((current) => current.map((item) => item.id === season.id ? { ...item, startDate: e.target.value } : item))} /></Field><Field label="To"><Input type="date" value={season.endDate} onChange={(e) => setSeasons((current) => current.map((item) => item.id === season.id ? { ...item, endDate: e.target.value } : item))} /></Field><NumberField label="Adjustment %" value={season.adjustmentPercent} onChange={(value) => setSeasons((current) => current.map((item) => item.id === season.id ? { ...item, adjustmentPercent: value } : item))} /><Field label="Enabled"><Switch checked={Boolean(season.active)} onCheckedChange={(active) => setSeasons((current) => current.map((item) => item.id === season.id ? { ...item, active } : item))} /></Field><Button variant="outline" disabled={busy === season.id} onClick={() => void savePricing("season", season)}><Save /> Save</Button></div>)}</div>
      </Panel>
      <Panel title="Rooms & accommodation inventory" description="Create, rename, price, link or deactivate every bookable unit. These records drive reservations, pricing and operations." icon={BedDouble}>
        <form onSubmit={addUnit} className="mb-5 grid gap-3 rounded-xl bg-blue-50 p-4 md:grid-cols-[1.2fr_130px_130px_120px_120px_auto] md:items-end"><Field label="New room / cottage"><Input name="name" required placeholder="Accommodation name" /></Field><Field label="Type"><select name="unitType" className="h-10 rounded-md border bg-white px-3 text-sm"><option>Room</option><option>Cottage</option></select></Field><NumberInput label="Adults" name="capacityAdults" value="2" /><NumberInput label="Children" name="capacityChildren" value="1" /><NumberInput label="Base rate" name="rate" value="0" /><Button className="bg-[#003b95]" disabled={busy === "new-unit"}><Plus /> Add</Button></form>
        <div className="space-y-3">{units.map((unit) => <div key={unit.id} className="grid gap-3 rounded-xl border p-4 lg:grid-cols-[1.2fr_120px_130px_105px_105px_120px_85px_auto] lg:items-end"><Field label="Name"><Input value={unit.name} onChange={(e) => setUnits((current) => current.map((item) => item.id === unit.id ? { ...item, name: e.target.value } : item))} /></Field><Field label="Type"><select value={unit.type} onChange={(e) => setUnits((current) => current.map((item) => item.id === unit.id ? { ...item, type: e.target.value as UnitConfig["type"] } : item))} className="h-10 rounded-md border bg-white px-3 text-sm"><option>Room</option><option>Cottage</option></select></Field><Field label="Linked parent"><select value={unit.parent ?? ""} onChange={(e) => setUnits((current) => current.map((item) => item.id === unit.id ? { ...item, parent: e.target.value || null } : item))} className="h-10 rounded-md border bg-white px-3 text-sm"><option value="">Independent</option>{units.filter((item) => item.id !== unit.id && item.type === "Cottage").map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><NumberField label="Adults" value={unit.capacityAdults} onChange={(value) => setUnits((current) => current.map((item) => item.id === unit.id ? { ...item, capacityAdults: value } : item))} /><NumberField label="Children" value={unit.capacityChildren} onChange={(value) => setUnits((current) => current.map((item) => item.id === unit.id ? { ...item, capacityChildren: value } : item))} /><NumberField label="Base rate" value={unit.rate} onChange={(value) => setUnits((current) => current.map((item) => item.id === unit.id ? { ...item, rate: value } : item))} /><Field label="Active"><Switch checked={Boolean(unit.active)} onCheckedChange={(active) => setUnits((current) => current.map((item) => item.id === unit.id ? { ...item, active } : item))} /></Field><Button variant="outline" disabled={busy === unit.id} onClick={() => void saveUnit(unit)}><Save /> Save</Button></div>)}</div>
      </Panel>
      <div className="grid gap-6 xl:grid-cols-2">
        <Panel title="Payment account" description="Configure the merchant identity used for payment requests. Secret keys remain outside the browser." icon={CreditCard}>
          <div className="grid gap-4 sm:grid-cols-2"><Field label="Provider"><select value={payment.provider} onChange={(e) => setPayment({ ...payment, provider: e.target.value })} className="h-10 rounded-md border bg-white px-3 text-sm"><option>Razorpay</option><option>Cashfree</option><option>PayU</option><option>Manual / UPI</option></select></Field><Field label="Display name"><Input value={payment.displayName} onChange={(e) => setPayment({ ...payment, displayName: e.target.value })} /></Field><Field label="Merchant ID"><Input value={payment.merchantId} onChange={(e) => setPayment({ ...payment, merchantId: e.target.value })} /></Field><Field label="Public key ID"><Input value={payment.keyId} onChange={(e) => setPayment({ ...payment, keyId: e.target.value })} /></Field><Field label="UPI ID"><Input value={payment.upiId} onChange={(e) => setPayment({ ...payment, upiId: e.target.value })} /></Field><Field label="Settlement account (last 4)"><Input maxLength={4} value={payment.settlementAccountMask} onChange={(e) => setPayment({ ...payment, settlementAccountMask: e.target.value.replace(/\D/g, "") })} /></Field><Field label="Mode"><select value={payment.mode} onChange={(e) => setPayment({ ...payment, mode: e.target.value })} className="h-10 rounded-md border bg-white px-3 text-sm"><option>Test</option><option>Live</option></select></Field><Field label="Collection enabled"><Switch checked={payment.active} onCheckedChange={(active) => setPayment({ ...payment, active })} /></Field></div><div className="mt-5 flex items-center justify-between gap-4 border-t pt-4"><p className="flex items-center gap-2 text-xs text-slate-500"><KeyRound className="size-4 text-emerald-700" /> Gateway secrets are configured separately as protected runtime secrets.</p><Button className="bg-[#003b95]" disabled={busy === "payment"} onClick={() => void savePayment()}><Save /> Save account</Button></div>
        </Panel>
        <Panel title="Create staff access" description="Staff sign in using their verified email after private Site access is shared; passwords are never stored by StayAxis." icon={UserCog}>
          <form onSubmit={addStaff} className="grid gap-4 sm:grid-cols-2"><Field label="Full name"><Input name="fullName" required /></Field><Field label="Email credential"><Input name="email" type="email" required /></Field><Field label="Phone"><Input name="phone" /></Field><Field label="Role"><select name="role" className="h-10 rounded-md border bg-white px-3 text-sm">{roles.map((role) => <option key={role}>{role}</option>)}</select></Field><Button className="bg-[#003b95] sm:col-span-2" disabled={busy === "staff"}><Plus /> Create staff access</Button></form>
          <div className="mt-5 divide-y border-t">{staff.map((member) => <div key={member.id} className="flex items-center gap-3 py-3"><span className="grid size-9 place-items-center rounded-lg bg-blue-50 text-[#003b95]"><ShieldCheck className="size-4" /></span><span className="min-w-0 flex-1"><strong className="block truncate text-sm">{member.fullName}</strong><span className="block truncate text-xs text-slate-500">{member.email} · {member.role}</span></span><Badge variant="outline" className={member.status === "Active" ? "border-emerald-200 bg-emerald-50 text-emerald-700" : "border-slate-200 bg-slate-50 text-slate-600"}>{member.status}</Badge><Button size="sm" variant="ghost" onClick={() => void setStaffStatus(member)}>{member.status === "Active" ? "Suspend" : "Activate"}</Button></div>)}</div>
        </Panel>
      </div>
    </section>
  </>;
}

function Panel({ title, description, icon: Icon, children }: { title: string; description: string; icon: typeof CreditCard; children: React.ReactNode }) { return <section className="rounded-2xl border bg-white p-5 shadow-sm"><div className="mb-5 flex items-start gap-3 border-b pb-4"><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-blue-50 text-[#003b95]"><Icon className="size-5" /></span><div><h2 className="font-bold">{title}</h2><p className="mt-1 text-sm text-slate-500">{description}</p></div></div>{children}</section>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="grid gap-2 text-sm font-semibold">{label}{children}</label>; }
function NumberField({ label, value, onChange }: { label: string; value: number; onChange: (value: number) => void }) { return <Field label={label}><Input type="number" value={value} onChange={(e) => onChange(Number(e.target.value) || 0)} /></Field>; }
function NumberInput({ label, name, value }: { label: string; name: string; value: string }) { return <Field label={label}><Input name={name} type="number" min="0" defaultValue={value} /></Field>; }
function Metric({ icon: Icon, label, value }: { icon: typeof CreditCard; label: string; value: string }) { return <div className="rounded-2xl border bg-white p-5"><div className="flex items-center justify-between"><span><span className="text-sm text-slate-500">{label}</span><strong className="mt-1 block text-2xl">{value}</strong></span><span className="grid size-10 place-items-center rounded-xl bg-blue-50 text-[#003b95]"><Icon className="size-5" /></span></div></div>; }
