"use client";

import { useEffect, useMemo, useState } from "react";
import { BadgeIndianRupee, BarChart3, Check, Megaphone, RefreshCw, Send, Sparkles, Target, X } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { money } from "./domain";

type MarketRate = { id: string; propertyName: string; stayDate: string; roomType: string; rate: number; source: string };
type Recommendation = { id: string; title: string; summary: string; rationale: string[]; targetDate: string; currentRate: number; proposedRate: number; promotion: { name?: string; benefits?: string[] }; audience: { segment?: string; filters?: string[] }; channels: string[]; confidence: number; status: string };
type Campaign = { id: string; name: string; status: string; channels: string[]; audience: { segment?: string }; createdAt: string };

export function AIRevenueCentre({ onNotice }: { onNotice: (value: string) => void }) {
  const [marketRates, setMarketRates] = useState<MarketRate[]>([]); const [recommendations, setRecommendations] = useState<Recommendation[]>([]); const [campaigns, setCampaigns] = useState<Campaign[]>([]); const [busy, setBusy] = useState("");
  const apply = (data: { marketRates?: MarketRate[]; recommendations?: Recommendation[]; campaigns?: Campaign[] }) => { setMarketRates(data.marketRates ?? []); setRecommendations(data.recommendations ?? []); setCampaigns(data.campaigns ?? []); };
  const load = async () => { try { const response = await fetch("/api/ai-revenue", { cache: "no-store" }); const data = await response.json(); if (response.ok) apply(data); } catch { onNotice("AI revenue workspace is temporarily unavailable."); } };
  // Load the latest persisted intelligence when this workspace opens.
  // eslint-disable-next-line react-hooks/set-state-in-effect, react-hooks/exhaustive-deps
  useEffect(() => { void load(); }, []);
  const generate = async () => { setBusy("generate"); try { const response = await fetch("/api/ai-revenue", { method: "POST" }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "Unable to generate recommendations."); apply(data); flash(onNotice, "A new explainable revenue recommendation was generated."); } catch (error) { flash(onNotice, error instanceof Error ? error.message : "Unable to generate recommendations."); } finally { setBusy(""); } };
  const review = async (id: string, action: "approve" | "reject") => { setBusy(id); try { const response = await fetch("/api/ai-revenue", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ id, action }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "Unable to review recommendation."); apply(data); flash(onNotice, action === "approve" ? "Recommendation approved. Campaign is queued until delivery connectors are live." : "Recommendation rejected; no rate or campaign was changed."); } catch (error) { flash(onNotice, error instanceof Error ? error.message : "Unable to review recommendation."); } finally { setBusy(""); } };
  const median = useMemo(() => { const values = marketRates.map((item) => item.rate).sort((a, b) => a - b); return values[Math.floor(values.length / 2)] ?? 0; }, [marketRates]);
  return <>
    <div className="mb-6 flex flex-wrap items-end justify-between gap-4"><div><p className="mb-1 text-xs font-bold uppercase tracking-[.14em] text-[#006ce4]">Revenue intelligence</p><h1 className="text-2xl font-bold tracking-tight sm:text-3xl">AI Revenue & Campaign Centre</h1><p className="mt-2 max-w-3xl text-sm text-slate-500">Compare market position, create explainable rate and promotion proposals, and require Admin approval before customer communication.</p></div><Button className="bg-[#003b95]" disabled={busy === "generate"} onClick={() => void generate()}><RefreshCw className={busy === "generate" ? "animate-spin" : ""} /> Generate recommendation</Button></div>
    <section className="mb-6 grid gap-4 md:grid-cols-4"><Metric icon={BarChart3} label="Market median" value={money(median)} note="Sample comp-set data" /><Metric icon={Sparkles} label="AI proposals" value={String(recommendations.filter((item) => item.status === "Proposed").length)} note="Awaiting human review" /><Metric icon={Megaphone} label="Approved campaigns" value={String(campaigns.length)} note="Controlled activation" /><Metric icon={Send} label="Messages sent" value="0" note="Connectors not live" /></section>
    <div className="mb-6 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900"><strong>Testing mode:</strong> competitor rates are clearly marked sample data. Live rates must come from an authorized rate-shopping provider or approved partner feed—never uncontrolled website scraping.</div>
    <section className="grid gap-6 xl:grid-cols-[.75fr_1.25fr]"><div className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><div><h2 className="font-bold">Nearby market snapshot</h2><p className="mt-1 text-sm text-slate-500">Comparable premium rooms</p></div><Badge variant="outline">Sample</Badge></div><div className="mt-5 space-y-3">{marketRates.map((item) => <div key={item.id} className="flex items-center gap-3 rounded-xl border p-3"><span className="grid size-9 place-items-center rounded-lg bg-blue-50 text-[#003b95]"><BadgeIndianRupee className="size-4" /></span><span className="min-w-0 flex-1"><strong className="block text-sm">{item.propertyName}</strong><span className="text-xs text-slate-500">{item.stayDate} · {item.source}</span></span><strong>{money(item.rate)}</strong></div>)}</div></div><div className="space-y-4">{recommendations.map((item) => <div key={item.id} className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2"><Badge className="bg-blue-50 text-[#003b95]">{item.confidence}% confidence</Badge><Badge variant="outline">{item.status}</Badge></div><h2 className="mt-3 text-lg font-bold">{item.title}</h2><p className="mt-2 text-sm leading-6 text-slate-600">{item.summary}</p></div><div className="rounded-xl bg-blue-50 px-4 py-3 text-right"><span className="block text-xs text-slate-500">Suggested rate</span><strong className="text-xl text-[#003b95]">{money(item.proposedRate)}</strong><span className="block text-xs text-slate-500">from {money(item.currentRate)}</span></div></div><div className="mt-5 grid gap-4 md:grid-cols-2"><Info title="Why this is proposed" icon={Sparkles} items={item.rationale} /><Info title="Campaign proposal" icon={Target} items={[item.promotion.name ?? "Targeted offer", ...(item.promotion.benefits ?? []), item.audience.segment ?? "Selected guests", item.channels.join(" + ")]} /></div>{item.status === "Proposed" && <div className="mt-5 flex flex-wrap justify-end gap-2 border-t pt-4"><Button variant="outline" disabled={busy === item.id} onClick={() => void review(item.id, "reject")}><X /> Reject</Button><Button className="bg-emerald-700" disabled={busy === item.id} onClick={() => void review(item.id, "approve")}><Check /> Admin approve</Button></div>}</div>)}</div></section>
    <section className="mt-6 rounded-2xl border bg-white p-5 shadow-sm"><h2 className="font-bold">Campaign approval queue</h2><p className="mt-1 text-sm text-slate-500">Approved campaigns remain blocked until the selected delivery connectors and consent rules are active.</p><div className="mt-4 divide-y">{campaigns.length === 0 ? <p className="py-6 text-center text-sm text-slate-500">No approved campaigns yet.</p> : campaigns.map((campaign) => <div key={campaign.id} className="flex flex-wrap items-center gap-3 py-4"><span className="grid size-9 place-items-center rounded-lg bg-emerald-50 text-emerald-700"><Megaphone className="size-4" /></span><span className="min-w-[180px] flex-1"><strong className="block text-sm">{campaign.name}</strong><span className="text-xs text-slate-500">{campaign.audience.segment} · {campaign.channels.join(", ")}</span></span><Badge variant="outline" className="border-amber-200 bg-amber-50 text-amber-700">{campaign.status}</Badge></div>)}</div></section>
  </>;
}

function Metric({ icon: Icon, label, value, note }: { icon: typeof Sparkles; label: string; value: string; note: string }) { return <div className="rounded-2xl border bg-white p-5"><div className="flex items-start justify-between"><div><p className="text-sm text-slate-500">{label}</p><strong className="mt-2 block text-2xl">{value}</strong><span className="mt-1 block text-xs text-slate-500">{note}</span></div><span className="grid size-10 place-items-center rounded-xl bg-blue-50 text-[#003b95]"><Icon className="size-5" /></span></div></div>; }
function Info({ title, icon: Icon, items }: { title: string; icon: typeof Sparkles; items: string[] }) { return <div className="rounded-xl bg-slate-50 p-4"><h3 className="flex items-center gap-2 text-sm font-bold"><Icon className="size-4 text-[#003b95]" />{title}</h3><div className="mt-3 space-y-2">{items.map((item) => <p key={item} className="flex gap-2 text-xs leading-5 text-slate-600"><Check className="mt-0.5 size-3.5 shrink-0 text-emerald-700" />{item}</p>)}</div></div>; }
function flash(setter: (value: string) => void, text: string) { setter(text); window.setTimeout(() => setter(""), 4200); }
