"use client";

import { useMemo, useState } from "react";
import { BadgeIndianRupee, Banknote, Check, Gift, IndianRupee, Medal, Plus, Search, Settings2, Sparkles, Star, UsersRound, WalletCards } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Switch } from "@/components/ui/switch";
import { cardOffers, loyaltyRewards, serviceCatalogue, serviceCategories, ServiceCategory } from "./commercial-config";
import { money } from "./domain";

export function ServiceCatalogueAdmin({ enabledServiceIds, onEnabledChange, onNotice }: { enabledServiceIds: string[]; onEnabledChange: (ids: string[]) => void; onNotice: (value: string) => void }) {
  const [search, setSearch] = useState("");
  const [category, setCategory] = useState<"All" | ServiceCategory>("All");
  const filtered = useMemo(() => serviceCatalogue.filter((service) => (category === "All" || service.category === category) && `${service.name} ${service.category}`.toLowerCase().includes(search.toLowerCase())), [category, search]);
  const flash = (text: string) => { onNotice(text); window.setTimeout(() => onNotice(""), 3200); };
  const toggle = (id: string, checked: boolean) => {
    const next = checked ? [...new Set([...enabledServiceIds, id])] : enabledServiceIds.filter((item) => item !== id);
    onEnabledChange(next);
    const service = serviceCatalogue.find((item) => item.id === id);
    flash(`${service?.name} ${checked ? "enabled for Cardamom Rock" : "removed from new quotations"}.`);
  };
  return <>
    <Heading eyebrow="Property configuration" title="Services & add-ons" description="Maintain one complete catalogue, then enable only the services offered by each resort." action={<Button className="bg-[#003b95]" onClick={() => flash("Custom service form opened for Cardamom Rock.")}><Plus /> Add custom service</Button>} />
    <section className="mb-6 grid gap-4 md:grid-cols-4"><Metric label="Industry services" value={String(serviceCatalogue.length)} note="Across 8 categories" icon={Settings2} /><Metric label="Enabled here" value={String(enabledServiceIds.length)} note="Shown in quotations" icon={Check} /><Metric label="Bookable online" value="9" note="Instant confirmation" icon={BadgeIndianRupee} /><Metric label="On request" value="4" note="Requires approval" icon={UsersRound} /></section>
    <div className="mb-5 rounded-2xl border bg-white p-4 shadow-sm"><div className="flex flex-col gap-3 lg:flex-row lg:items-center"><div className="relative flex-1"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-slate-400" /><Input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search transport, dining, experiences…" className="pl-10" /></div><div className="flex gap-2 overflow-x-auto pb-1 lg:max-w-[70%]">{(["All", ...serviceCategories] as const).map((item) => <button key={item} onClick={() => setCategory(item)} className={`shrink-0 rounded-full px-3 py-2 text-xs font-bold transition ${category === item ? "bg-[#003b95] text-white" : "bg-slate-100 text-slate-600 hover:bg-slate-200"}`}>{item}</button>)}</div></div></div>
    <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{filtered.map((service) => { const enabled = enabledServiceIds.includes(service.id); return <div key={service.id} className={`rounded-2xl border bg-white p-5 transition ${enabled ? "border-blue-200 shadow-sm" : "opacity-75"}`}><div className="flex items-start gap-4"><span className={`grid size-10 shrink-0 place-items-center rounded-xl ${enabled ? "bg-blue-50 text-[#003b95]" : "bg-slate-100 text-slate-400"}`}><ServiceIcon category={service.category} /></span><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-3"><div><Badge variant="outline" className="mb-2 text-[10px]">{service.category}</Badge><h2 className="text-sm font-bold">{service.name}</h2></div><Switch checked={enabled} onCheckedChange={(checked) => toggle(service.id, checked)} aria-label={`Enable ${service.name}`} /></div><div className="mt-4 flex items-end justify-between"><span><span className="block text-lg font-bold">{money(service.price)}</span><span className="text-xs text-slate-500">{service.unit}</span></span><button onClick={() => flash(`Pricing editor opened for ${service.name}.`)} className="text-xs font-bold text-[#003b95]">Edit price</button></div></div></div></div>; })}</section>
    {filtered.length === 0 && <div className="rounded-2xl border bg-white p-12 text-center text-sm text-slate-500">No services match this search.</div>}
  </>;
}

export function LoyaltyAndOffers({ onNotice }: { onNotice: (value: string) => void }) {
  const [loyaltyOn, setLoyaltyOn] = useState(true);
  const [activeOffers, setActiveOffers] = useState(["hdfc", "icici", "upi"]);
  const flash = (text: string) => { onNotice(text); window.setTimeout(() => onNotice(""), 3200); };
  const toggleOffer = (id: string, checked: boolean) => setActiveOffers((current) => checked ? [...new Set([...current, id])] : current.filter((item) => item !== id));
  return <>
    <Heading eyebrow="Guest retention" title="Loyalty, rewards & card offers" description="Reward direct bookings, improve repeat stays and run payment offers without changing room rates." action={<div className="flex items-center gap-3 rounded-xl border bg-white px-4 py-2"><span className="text-sm font-semibold">Program active</span><Switch checked={loyaltyOn} onCheckedChange={(checked) => { setLoyaltyOn(checked); flash(`StayAxis Rewards ${checked ? "enabled" : "paused"}.`); }} /></div>} />
    <section className="mb-6 grid gap-4 md:grid-cols-4"><Metric label="Active members" value="1,284" note="+86 this month" icon={UsersRound} /><Metric label="Repeat booking rate" value="31%" note="+6 points YoY" icon={Star} /><Metric label="Points issued" value="4.82L" note="₹96,400 liability" icon={Sparkles} /><Metric label="Redemption rate" value="18.6%" note="Healthy utilization" icon={Gift} /></section>
    <section className="grid gap-6 xl:grid-cols-[1fr_.85fr]">
      <div className="space-y-6">
        <div className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-4"><div><h2 className="font-bold">Earning rules</h2><p className="mt-1 text-sm text-slate-500">Points post after check-out and exclude refunded amounts.</p></div><Button variant="outline" size="sm" onClick={() => flash("Loyalty earning and expiry rules opened.")}>Edit rules</Button></div><div className="mt-5 grid gap-3 sm:grid-cols-3"><Rule value="5 points" label="per ₹100 spent" /><Rule value="2× points" label="on direct bookings" /><Rule value="18 months" label="points validity" /></div><div className="mt-5 grid gap-3 sm:grid-cols-3"><Tier name="Explorer" requirement="0–4,999 points" benefit="Member-only rate" tone="bg-slate-100 text-slate-700" /><Tier name="Gold" requirement="5,000–14,999" benefit="5% bonus points" tone="bg-amber-50 text-amber-800" /><Tier name="Platinum" requirement="15,000+ points" benefit="10% bonus + upgrade" tone="bg-blue-50 text-[#003b95]" /></div></div>
        <div className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><div><h2 className="font-bold">Reward catalogue</h2><p className="mt-1 text-sm text-slate-500">Members can redeem at quotation, booking or pre-arrival.</p></div><Button variant="outline" size="sm" onClick={() => flash("New loyalty reward form opened.")}><Plus /> New reward</Button></div><div className="mt-5 grid gap-3 sm:grid-cols-2">{loyaltyRewards.filter((reward) => reward.id !== "none").map((reward) => <div key={reward.id} className="flex items-center gap-3 rounded-xl border p-4"><span className="grid size-10 place-items-center rounded-xl bg-[#fff3cd] text-amber-700"><Gift className="size-4" /></span><span className="min-w-0 flex-1"><strong className="block text-sm">{reward.name}</strong><span className="text-xs text-slate-500">Value {money(reward.value)}</span></span><Badge className="bg-[#003b95] text-white">{reward.points.toLocaleString("en-IN")} pts</Badge></div>)}</div></div>
      </div>
      <div className="space-y-6">
        <div className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><div><h2 className="font-bold">Card & payment offers</h2><p className="mt-1 text-sm text-slate-500">Eligibility is verified during gateway payment.</p></div><WalletCards className="text-[#003b95]" /></div><div className="mt-5 space-y-3">{cardOffers.filter((offer) => offer.id !== "none").map((offer) => <div key={offer.id} className="rounded-xl border p-4"><div className="flex items-start gap-3"><span className="grid size-9 place-items-center rounded-lg bg-blue-50 text-[#003b95]"><Banknote className="size-4" /></span><div className="min-w-0 flex-1"><strong className="block text-sm">{offer.name}</strong><span className="mt-1 block text-xs text-slate-500">Min. booking {money(offer.minimum)} · maximum benefit {money(offer.cap)}</span></div><Switch checked={activeOffers.includes(offer.id)} onCheckedChange={(checked) => toggleOffer(offer.id, checked)} aria-label={`Enable ${offer.name}`} /></div></div>)}</div></div>
        <div className="overflow-hidden rounded-2xl bg-gradient-to-br from-[#003b95] to-[#006ce4] text-white shadow-lg"><div className="p-6"><div className="flex items-start justify-between"><span className="grid size-11 place-items-center rounded-xl bg-white/15"><Medal /></span><Badge className="bg-[#febb02] text-[#3b2f00]">Gold member</Badge></div><p className="mt-8 text-sm text-white/65">ANJALI MENON</p><p className="mt-1 text-3xl font-bold">7,450 points</p><div className="mt-6 h-2 rounded-full bg-white/15"><div className="h-full w-[62%] rounded-full bg-[#febb02]" /></div><div className="mt-2 flex justify-between text-xs text-white/60"><span>Gold</span><span>7,550 pts to Platinum</span></div></div><div className="border-t border-white/15 bg-white/5 px-6 py-4 text-sm">Available value: <strong>up to ₹3,200</strong> on the next stay</div></div>
      </div>
    </section>
  </>;
}

function Heading({ eyebrow, title, description, action }: { eyebrow: string; title: string; description: string; action?: React.ReactNode }) { return <div className="mb-6 flex flex-wrap items-end justify-between gap-4"><div><p className="mb-1 text-xs font-bold uppercase tracking-[.14em] text-[#006ce4]">{eyebrow}</p><h1 className="text-2xl font-bold tracking-tight sm:text-3xl">{title}</h1><p className="mt-2 max-w-2xl text-sm text-slate-500">{description}</p></div>{action}</div>; }
function Metric({ label, value, note, icon: Icon }: { label: string; value: string; note: string; icon: typeof Settings2 }) { return <div className="rounded-2xl border bg-white p-5"><div className="flex items-start justify-between"><div><p className="text-sm text-slate-500">{label}</p><p className="mt-2 text-2xl font-bold">{value}</p><p className="mt-1 text-xs text-slate-500">{note}</p></div><span className="grid size-10 place-items-center rounded-xl bg-blue-50 text-[#003b95]"><Icon className="size-5" /></span></div></div>; }
function Rule({ value, label }: { value: string; label: string }) { return <div className="rounded-xl bg-blue-50 p-4"><strong className="block text-lg text-[#003b95]">{value}</strong><span className="mt-1 block text-xs text-slate-500">{label}</span></div>; }
function Tier({ name, requirement, benefit, tone }: { name: string; requirement: string; benefit: string; tone: string }) { return <div className={`rounded-xl p-4 ${tone}`}><strong className="block">{name}</strong><span className="mt-1 block text-xs opacity-70">{requirement}</span><span className="mt-3 block text-xs font-semibold">{benefit}</span></div>; }
function ServiceIcon({ category }: { category: ServiceCategory }) { const map: Record<ServiceCategory, typeof IndianRupee> = { Transport: WalletCards, Dining: BadgeIndianRupee, Experiences: Sparkles, Wellness: Star, Celebrations: Gift, Family: UsersRound, Convenience: Settings2, Events: Medal }; const Icon = map[category]; return <Icon className="size-4" />; }
