"use client";

import { useState } from "react";
import { Bot, Check, CircleDollarSign, ExternalLink, Globe2, MessageCircleMore, RefreshCw, Send, Sparkles } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Switch } from "@/components/ui/switch";
import { Reservation, money } from "./domain";

export function DirectBookings({ onNotice }: { onNotice: (value: string) => void }) {
  return <>
    <Heading eyebrow="Growth engine" title="Direct bookings" description="Manage the resort website funnel, offers and commission-free bookings from one place." action={<Button className="bg-[#003b95]" onClick={() => flash(onNotice, "Booking-engine preview opened for review.")}><ExternalLink /> Preview booking engine</Button>} />
    <section className="grid gap-4 md:grid-cols-4">
      <Metric label="Website sessions" value="1,842" change="+18% this month" />
      <Metric label="Booking conversion" value="4.8%" change="+0.7 points" />
      <Metric label="Direct revenue" value="₹3.84L" change="62% of total" />
      <Metric label="Commission saved" value="₹57,600" change="vs OTA equivalent" />
    </section>
    <section className="mt-6 grid gap-6 xl:grid-cols-[1.1fr_.9fr]">
      <div className="rounded-2xl border bg-white p-5 shadow-sm">
        <div className="flex items-start justify-between"><div><h2 className="font-bold">Booking funnel</h2><p className="mt-1 text-sm text-slate-500">Last 30 days</p></div><Badge className="bg-emerald-50 text-emerald-700">Healthy</Badge></div>
        <div className="mt-7 space-y-4"><Funnel label="Website visitors" value="1,842" width="100%" /><Funnel label="Availability searched" value="786" width="73%" /><Funnel label="Guest details entered" value="164" width="48%" /><Funnel label="Bookings completed" value="88" width="31%" /></div>
      </div>
      <div className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><div><h2 className="font-bold">Live offers</h2><p className="mt-1 text-sm text-slate-500">Visible in the direct booking flow</p></div><Button size="sm" variant="outline">New offer</Button></div><div className="mt-5 space-y-3"><Offer name="Monsoon Escape" detail="Stay 2 nights · breakfast included" value="12% off" /><Offer name="Early Bird" detail="Book 21 days ahead" value="8% off" /><Offer name="Direct Advantage" detail="Free room upgrade when available" value="Active" /></div></div>
    </section>
    <section className="mt-6 rounded-2xl border bg-[#004bad] p-5 text-white"><div className="flex flex-wrap items-center gap-5"><span className="grid size-12 place-items-center rounded-xl bg-[#febb02] text-[#003b95]"><Globe2 /></span><div className="min-w-[220px] flex-1"><h2 className="font-bold">Google Hotels connection</h2><p className="mt-1 text-sm text-white/60">Rates and direct availability are ready to publish once the property profile is connected.</p></div><Button className="bg-[#febb02] text-[#003b95] hover:bg-[#ffca28]" onClick={() => flash(onNotice, "Google Hotels connection checklist prepared.")}>Connect property</Button></div></section>
  </>;
}

export function ChannelManager({ onNotice }: { onNotice: (value: string) => void }) {
  const [syncing, setSyncing] = useState(false);
  const sync = () => { setSyncing(true); setTimeout(() => { setSyncing(false); flash(onNotice, "All connected channels synchronized successfully."); }, 900); };
  return <>
    <Heading eyebrow="Distribution" title="Channel manager" description="One inventory pool across direct bookings and OTAs, with linked-room protection." action={<Button className="bg-[#003b95]" onClick={sync} disabled={syncing}><RefreshCw className={syncing ? "animate-spin" : ""} /> {syncing ? "Syncing…" : "Sync all channels"}</Button>} />
    <section className="mb-6 grid gap-4 md:grid-cols-4"><Metric label="Channels live" value="4" change="All connected" /><Metric label="Rooms distributed" value="6" change="1 linked cottage" /><Metric label="Sync success" value="99.8%" change="Last 30 days" /><Metric label="Conflicts prevented" value="7" change="Linked inventory rules" /></section>
    <div className="overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="grid grid-cols-[1.2fr_.7fr_.7fr_.7fr] gap-3 border-b bg-slate-50 px-5 py-3 text-xs font-bold uppercase tracking-wider text-slate-500"><span>Channel</span><span>Status</span><span>Last sync</span><span>Bookings</span></div>{[
      ["StayAxis Direct", "Booking engine + website", "Live", "Now", "88"], ["Booking.com", "Rates, inventory & reservations", "Live", "2 min", "34"], ["MakeMyTrip / Goibibo", "Rates, inventory & reservations", "Live", "3 min", "21"], ["Agoda", "Rates, inventory & reservations", "Attention", "18 min", "9"]
    ].map(([name, detail, status, syncAt, bookings]) => <div key={name} className="grid grid-cols-[1.2fr_.7fr_.7fr_.7fr] items-center gap-3 border-b px-5 py-4 last:border-0"><div><strong className="block text-sm">{name}</strong><span className="text-xs text-slate-500">{detail}</span></div><Badge variant="outline" className={status === "Live" ? "w-fit border-emerald-200 bg-emerald-50 text-emerald-700" : "w-fit border-amber-200 bg-amber-50 text-amber-700"}>{status}</Badge><span className="text-sm text-slate-600">{syncAt}</span><strong className="text-sm">{bookings}</strong></div>)}</div>
    <section className="mt-6 grid gap-6 xl:grid-cols-[1fr_.9fr]"><div className="rounded-2xl border bg-white p-5"><h2 className="font-bold">Linked inventory guard</h2><p className="mt-1 text-sm text-slate-500">Cedar 2-BHK and its child rooms are controlled by one availability service.</p><div className="mt-5 grid grid-cols-3 gap-3"><InventoryCell name="Full cottage" status="Occupied" /><InventoryCell name="Room A" status="Sold" /><InventoryCell name="Room B" status="Auto-blocked" /></div><div className="mt-4 rounded-xl bg-emerald-50 p-3 text-sm text-emerald-800"><Check className="mr-2 inline size-4" />Overbooking protection is active across every channel.</div></div><div className="rounded-2xl border bg-white p-5"><h2 className="font-bold">Sync activity</h2><div className="mt-4 space-y-4"><Timeline text="Booking.com reservation STX-1041 imported" time="2 min ago" /><Timeline text="Pepper Cottage rates published to 4 channels" time="9 min ago" /><Timeline text="Cedar child inventory recalculated" time="16 min ago" /></div></div></section>
  </>;
}

export function WhatsAppWorkflows({ onNotice }: { onNotice: (value: string) => void }) {
  const [enabled, setEnabled] = useState<Record<string, boolean>>({ confirm: true, prearrival: true, payment: true, review: false });
  const flows = [
    ["confirm", "Booking confirmation", "Immediately after confirmation", "Reservation details + directions"],
    ["prearrival", "Pre-arrival welcome", "24 hours before check-in", "Arrival time + self check-in link"],
    ["payment", "Payment reminder", "When balance remains unpaid", "Secure gateway payment link"],
    ["review", "Review request", "4 hours after check-out", "Google review link + feedback"],
  ];
  return <>
    <Heading eyebrow="Guest communication" title="WhatsApp workflows" description="Automate useful guest messages while keeping conversations visible to the front desk." action={<Button className="bg-[#1f9d61]" onClick={() => flash(onNotice, "WhatsApp Business connection setup opened.")}><MessageCircleMore /> WhatsApp connected</Button>} />
    <section className="mb-6 grid gap-4 md:grid-cols-4"><Metric label="Messages sent" value="284" change="This month" /><Metric label="Delivery rate" value="98.6%" change="279 delivered" /><Metric label="Guest replies" value="46" change="16.2% response" /><Metric label="Recovered bookings" value="7" change="₹54,800 revenue" /></section>
    <div className="grid gap-6 xl:grid-cols-[1fr_.75fr]"><div className="overflow-hidden rounded-2xl border bg-white"><div className="border-b p-5"><h2 className="font-bold">Automation workflows</h2><p className="mt-1 text-sm text-slate-500">Switch workflows on or off without changing templates.</p></div><div className="divide-y">{flows.map(([id, name, trigger, content]) => <div key={id} className="flex items-center gap-4 p-5"><span className="grid size-10 place-items-center rounded-xl bg-emerald-50 text-emerald-700"><Send className="size-4" /></span><div className="min-w-0 flex-1"><strong className="block text-sm">{name}</strong><span className="block text-xs text-slate-500">{trigger} · {content}</span></div><Switch checked={enabled[id]} onCheckedChange={(checked) => setEnabled(v => ({...v, [id]: checked}))} aria-label={`Toggle ${name}`} /></div>)}</div></div><div className="rounded-2xl border bg-white p-5"><div className="flex items-center justify-between"><div><h2 className="font-bold">Guest conversation</h2><p className="mt-1 text-sm text-slate-500">Anjali Menon · STX-1042</p></div><Badge className="bg-emerald-50 text-emerald-700">WhatsApp</Badge></div><div className="mt-5 space-y-3 rounded-2xl bg-[#eef4ff] p-4"><Message side="out" text="Your stay at Cardamom Rock is confirmed for 17 Sep. Tap here for directions and check-in details." /><Message side="in" text="Thank you. Can we check in around 12:30 PM?" /><Message side="out" text="Yes, early check-in is noted. We’ll message you when the cottage is ready." /></div><Button variant="outline" className="mt-4 w-full" onClick={() => flash(onNotice, "Conversation opened in the shared guest inbox.")}>Open shared inbox</Button></div></div>
  </>;
}

export function RevenueControl({ reservations, onNotice }: { reservations: Reservation[]; onNotice: (value: string) => void }) {
  const [applied, setApplied] = useState(false); const total = reservations.reduce((s,r)=>s+r.amount,0);
  return <>
    <Heading eyebrow="Commercial control" title="Revenue management" description="Use occupancy, pickup and channel mix to control rates—not guesswork." action={<Button className="bg-[#003b95]" onClick={() => { setApplied(true); flash(onNotice, "Recommended weekend rates applied to the pricing draft."); }}><Sparkles /> {applied ? "Suggestions applied" : "Apply AI suggestions"}</Button>} />
    <section className="mb-6 grid gap-4 md:grid-cols-4"><Metric label="Occupancy" value="72%" change="+8% week-on-week" /><Metric label="ADR" value="₹7,860" change="+₹420 vs last week" /><Metric label="RevPAR" value="₹5,659" change="+13.4%" /><Metric label="Booked revenue" value={money(total)} change="Current reservation set" /></section>
    <section className="grid gap-6 xl:grid-cols-[1.25fr_.75fr]"><div className="overflow-hidden rounded-2xl border bg-white"><div className="border-b p-5"><h2 className="font-bold">7-day demand calendar</h2><p className="mt-1 text-sm text-slate-500">Recommended public rate by occupancy and booking pace</p></div><div className="overflow-x-auto p-5"><div className="grid min-w-[700px] grid-cols-[140px_repeat(7,1fr)] gap-2 text-center"><span />{["Thu 17","Fri 18","Sat 19","Sun 20","Mon 21","Tue 22","Wed 23"].map(x=><strong key={x} className="p-2 text-xs text-slate-500">{x}</strong>)}<strong className="py-4 text-left text-sm">Pepper Cottage</strong>{[9200,9900,10600,9900,8800,8800,9200].map((v,i)=><Rate key={i} value={v} hot={i===2} />)}<strong className="py-4 text-left text-sm">Cardamom Suite</strong>{[8200,8600,9200,8600,7800,7800,8200].map((v,i)=><Rate key={i} value={v} hot={i===2} />)}<strong className="py-4 text-left text-sm">Cedar 2-BHK</strong>{[12400,13200,14800,13600,11800,11800,12400].map((v,i)=><Rate key={i} value={v} hot={i===2} />)}</div></div></div><div className="rounded-2xl bg-[#004bad] p-5 text-white"><span className="grid size-11 place-items-center rounded-xl bg-[#febb02] text-[#003b95]"><Bot /></span><h2 className="mt-5 font-bold">Pricing opportunities</h2><div className="mt-4 space-y-3"><Insight title="High Saturday pickup" detail="Increase premium units by 8–12%." value="+₹18.6K" /><Insight title="Soft Monday demand" detail="Open a 2-night direct offer." value="+4 bookings" /><Insight title="OTA mix increasing" detail="Keep direct rate ₹350 lower." value="Save ₹7.2K" /></div></div></section>
  </>;
}

function Heading({ eyebrow, title, description, action }: { eyebrow:string; title:string; description:string; action?:React.ReactNode }) { return <div className="mb-6 flex flex-wrap items-end justify-between gap-4"><div><p className="mb-1 text-xs font-bold uppercase tracking-[.14em] text-emerald-700">{eyebrow}</p><h1 className="text-2xl font-bold tracking-tight sm:text-3xl">{title}</h1><p className="mt-2 max-w-2xl text-sm text-slate-500">{description}</p></div>{action}</div>; }
function Metric({label,value,change}:{label:string;value:string;change:string}) { return <div className="rounded-2xl border bg-white p-5"><p className="text-sm text-slate-500">{label}</p><p className="mt-3 text-2xl font-bold">{value}</p><p className="mt-1 text-xs text-emerald-700">{change}</p></div>; }
function Funnel({label,value,width}:{label:string;value:string;width:string}) { return <div><div className="mb-2 flex justify-between text-sm"><span>{label}</span><strong>{value}</strong></div><div className="h-10 rounded-xl bg-slate-100"><div className="flex h-full items-center rounded-xl bg-[#004bad] px-3 text-xs font-semibold text-white" style={{width}}>{width}</div></div></div>; }
function Offer({name,detail,value}:{name:string;detail:string;value:string}) { return <div className="flex items-center gap-3 rounded-xl border p-4"><span className="grid size-9 place-items-center rounded-lg bg-amber-50 text-amber-700"><CircleDollarSign className="size-4" /></span><span className="min-w-0 flex-1"><strong className="block text-sm">{name}</strong><span className="text-xs text-slate-500">{detail}</span></span><Badge variant="outline">{value}</Badge></div>; }
function InventoryCell({name,status}:{name:string;status:string}) { return <div className="rounded-xl border bg-slate-50 p-3"><p className="text-xs font-bold">{name}</p><p className="mt-2 text-xs text-slate-500">{status}</p></div>; }
function Timeline({text,time}:{text:string;time:string}) { return <div className="flex gap-3"><span className="mt-1 size-2 rounded-full bg-emerald-500" /><div><p className="text-sm font-medium">{text}</p><p className="mt-1 text-xs text-slate-500">{time}</p></div></div>; }
function Message({side,text}:{side:"in"|"out";text:string}) { return <div className={`max-w-[88%] rounded-2xl px-4 py-3 text-sm leading-5 ${side==="out"?"ml-auto rounded-br-sm bg-[#d7f7c5]":"rounded-bl-sm bg-white"}`}>{text}</div>; }
function Rate({value,hot}:{value:number;hot?:boolean}) { return <button className={`rounded-xl border p-3 text-xs font-bold transition hover:-translate-y-0.5 ${hot?"border-[#febb02] bg-[#e8f1ff] text-emerald-900":"bg-slate-50"}`}>₹{(value/1000).toFixed(1)}K{hot&&<span className="mt-1 block text-[10px] text-emerald-700">↑ suggested</span>}</button>; }
function Insight({title,detail,value}:{title:string;detail:string;value:string}) { return <div className="rounded-xl bg-white/8 p-4"><div className="flex justify-between gap-3"><strong className="text-sm">{title}</strong><span className="shrink-0 text-xs font-bold text-[#febb02]">{value}</span></div><p className="mt-2 text-xs leading-5 text-white/55">{detail}</p></div>; }
function flash(setter:(value:string)=>void,text:string) { setter(text); setTimeout(()=>setter(""),3800); }
